# coding: utf-8

"""
    Google Forms Creation & Review System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_approve_survey_surveys_survey_id_approve_post(self) -> None:
        """Test case for approve_survey_surveys_survey_id_approve_post

        Approve Survey
        """
        pass

    def test_create_survey_surveys_post(self) -> None:
        """Test case for create_survey_surveys_post

        Create Survey
        """
        pass

    def test_list_surveys_surveys_get(self) -> None:
        """Test case for list_surveys_surveys_get

        List Surveys
        """
        pass

    def test_read_root_get(self) -> None:
        """Test case for read_root_get

        Read Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
